<!-- Stylesheets -->
<link rel="stylesheet" href="http://test.jmls.edu/testalumni/css/main.css" media="screen" type="text/css">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic,700italic" type="text/css">

<!-- HTML5 Shiv -->
<!--[if lt IE 9]>
	<script src="http://test.jmls.edu/testalumni/js/html5shiv.js"></script>
<![endif]-->

<!-- Scripts -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://test.jmls.edu/testalumni/js/modernizr.custom.min.js"></script>			
<script src="http://test.jmls.edu/testalumni/js/responsiveslides.min.js"></script>
<script src="http://test.jmls.edu/testalumni/js/responsive-nav.min.js"></script>
<script src="http://test.jmls.edu/testalumni/js/respond.min.js"></script>