<aside class="sidebar">	
	<div class="grid-wrap">

		<div class="grid-col bp2-col-1-2 bp3-col-1-1">
		  <!-- Social Media Icons -->
		  <div class="module">
				<div class="header-bar header-bar-gray">Connect Online</div>
				<div class="social social-sidebar">
					<div class="social-icon">
						<a href="https://www.facebook.com/JMLSAlumni" title="Facebook" target="_blank"><img class="social-icon-img-small" src="http://test.jmls.edu/testalumni/images/icon-facebook-color.svg" alt="Facebook"></a>
					</div>
					<div class="social-icon">
						<a href="https://twitter.com/JMLSAlumni" title="Twitter" target="_blank"><img class="social-icon-img-small" src="http://test.jmls.edu/testalumni/images/icon-twitter-color.svg" alt="Twitter"></a>
					</div>
					<div class="social-icon">
						<a href="http://www.linkedin.com/groups?gid=121368&trk=myg_ugrp_ovr" title="LinkedIn" target="_blank"><img class="social-icon-img-small" src="http://test.jmls.edu/testalumni/images/icon-linkedin-color.svg" alt="LinkedIn"></a>
					</div>
					<div class="social-icon">
						<a href="http://www.youtube.com/jmlschicago" title="YouTube" target="_blank"><img class="social-icon-img-small" src="http://test.jmls.edu/testalumni/images/icon-youtube-color.svg" alt="YouTube"></a>
					</div>
					<div class="social-icon">
						<a href="http://www.flickr.com/photos/43883549@N08/" title="Flickr" target="_blank"><img class="social-icon-img-small" src="http://test.jmls.edu/testalumni/images/icon-flickr-color.svg" alt="Flickr"></a>
					</div>
				</div>				
			</div>
		</div><!-- .grid-col -->

		<div class="grid-col bp2-col-1-2 bp3-col-1-1">
		  <!-- Briefcase Issue -->
		  <div class="module">
				<div class="header-bar header-bar-gold">Briefcase</div>
				<div class="feature-box-color feature-box-gold text-small">
					<div class="feature-box-col feature-box-col-1-2 text-small">		
						Highlights alumni achievements and updates to JMLS development initiatives.
					</div>
					<div class="feature-box-col feature-box-col-1-2 feature-box-col-raised text-center">	
						<a href="http://news.jmls.edu/briefcase/" target="_blank"><img class="mar-bot-smallest box-shadow-1" src="http://test.jmls.edu/testalumni/images/briefcase-cover.jpg" alt="Briefcase | The John Marshall Law School"></a>													
						<div>
							<a href="http://news.jmls.edu/briefcase/" target="_blank" class="btn btn-small btn-red bold">Read Now</a>
						</div>
					</div>						
				</div>
			</div>
		</div><!-- .grid-col -->	

		<div class="grid-col bp2-col-1-2 bp3-col-1-1">
			<div class="module">
				<div class="header-bar header-bar-gold">Contact Us</div>
			  <div class="feature-box feature-box-color feature-box-gold line-height-main-alt">
					315 S Plymouth Court<br>
					Chicago, IL 60604<br>
					312.427.2737<br>
					<a href="mailto:alumni@jmls.edu">alumni@jmls.edu
			  </div>
			</div>
		</div><!-- .grid-col -->

	</div><!-- .grid-wrap -->	
	
</aside>